### ISSUE TITLE
Git repository

### ISSUE THREAD

**Issue by bogdanlupashko** [Kal1na-w/FractionCalculator#4]
1. Add gitignore file
2. Add readme.md 
(should contain:
- description
- examples how the project could be used
- environment like min java version and other
- contact info)
3. remove from git compiled files and IDE settings

**Comment by bogdanlupashko** [comment]
@Kal1na-w  please add changes separately by issues
and follow commit message like this one
```
ISSUE-4: Git repository:
- added ....
- removed ... 
... 
```

**Comment by Kal1na-w** [comment]
fixed on commit cc2ae1db7ea9c5e468ce9e11a65b4101ed996fba
