### ISSUE TITLE
ua.od.atomspace.validation.ExpressionValidation

### ISSUE THREAD

**Issue by bogdanlupashko** [Kal1na-w/FractionCalculator#7]
1. make sure you really need StringBuilder instead of String in this class(and please check other classes)
2. ua.od.atomspace.validation.ExpressionValidation#addSpaces
find another way to implement such things.

**Comment by Kal1na-w** [comment]
What do you mean?
```java
private String addSpaces(String expression) {
        return " " + expression + " ";
 }
```
Is it correct?

**Comment by bogdanlupashko** [comment]
both solutions are correct and do the same.
but the latest at least is more readable.
also pay attention on refactored addSpaces method.
If this method is not public and it contains only one line of code and it used in one place, probably you could remove it as unnecessary.
